Use proper tempfile for capturing stderr

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -42,10 +42,11 @@ echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Test for libv8
-echo "#include $PKG_TEST_HEADER" | ${CXXCPP} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - >/dev/null 2>stderr.out
+tmpfile=$(mktemp)
+echo "#include $PKG_TEST_HEADER" | ${CXXCPP} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - >/dev/null 2>$tmpfile
 if [ $? -ne 0 ]; then
   echo "------------------------- ANTICONF ERROR ---------------------------"
-  echo "Configuration failed because $PKG_CONFIG_NAME was not found. Try installing:"
+  echo "Configuration failed because libv8 engine was not found. Try installing:"
   echo " * deb: $PKG_DEB_NAME (Debian / Ubuntu)"
   echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
   echo " * brew: $PKG_BREW_NAME (OSX)"
@@ -53,8 +54,8 @@ if [ $? -ne 0 ]; then
   echo "To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:"
   echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
   echo "--------------------------------------------------------------------"
-  cat stderr.out && rm -f stderr.out
-  exit 1;
+  cat $tmpfile
+  exit 1
 fi
 
 # Test for legacy libv8 version
